export const content = {
    en: {
        heading: "Driver Information",
        country: "Your Home Country",
        street: "Street",
        streetplaceholder: "Home address...",
        postal: "Postal Code",
        city: "City",
        phone: "Phone Number",
        email: "Email",
        emailplaceholder: "Your@email.com",
        submit: "Submit",
        reset: "Reset fields",
        emailerror: "Enter a valid email",
        phoneerror: "Phone number is to long",
        confirmation: "Thank you! Enjoy your SIXT Experience."
    },
    es: {
        heading: "Información del Conductor",
        country: "Tu país de origen",
        street: "Calle",
        streetplaceholder: "Direccion de casa...",
        postal: "Código postal",
        city: "Ciudad",
        phone: "Número de teléfono",
        email: "Email",
        emailplaceholder: "Tu@email.com",
        submit: "Entregar",
        reset: "Reestablecer campos",
        emailerror: "Introduzca un correo electrónico válido",
        phoneerror: "El número de teléfono es demasiado largo",
        confirmation: "Gracias! Disfrute de su experiencia SIXT."
    },
    fr: {
        heading: "Informations sur le conducteur",
        country: "Votre pays d'origine",
        street: "Rue",
        streetplaceholder: "Adresse du domicile...",
        postal: "code postal",
        city: "Ville",
        phone: "Numéro de téléphone",
        email: "E-mail",
        emailplaceholder: "Votre@email.com",
        submit: "soumettre",
        reset: "Réinitialisation des champs",
        emailerror: "Entrer un email valide",
        phoneerror: "Le numéro de téléphone est trop long",
        confirmation: "Merci! Profitez de votre expérience SIXT."
    },
    de: {
        heading: "Fahrerinformationen",
        country: "Ihr Heimatland",
        street: "Straße",
        streetplaceholder: "Heimatadresse...",
        postal: "Postleitzahl",
        city: "Stadt",
        phone: "Telefonnummer",
        email: "Email",
        emailplaceholder: "Ihre@email.com",
        submit: "einreichen",
        reset: "Felder zurücksetzen",
        emailerror: "Geben Sie eine gültige E-Mail-Adresse ein",
        phoneerror: "Telefonnummer ist zu lang",
        confirmation: "Danke dir! Genießen Sie Ihr SIXT-Erlebnis."
    },
    no: {
        heading: "Førerinformasjon",
        country: "Land",
        street: "Gate",
        streetplaceholder: "Hjemme adresse...",
        postal: "Postnummer",
        city: "Poststed",
        phone: "Telefon nummer",
        email: "Epost",
        emailplaceholder: "din@epost.no",
        submit: "Send",
        reset: "Reset felter",
        emailerror: "Skriv inn en gyldig epost",
        phoneerror: "Telefon nummer er for langt",
        confirmation: "Takk skal du ha! Nyt SIXT-opplevelsen din."
    }
}
